import { preprocessScript } from "./preprocess.js";
import { createFilter } from "vite";

/**
 * Preprocessor for Brefer syntax, using variable prefixes to handle reactivity.
 * It avoids the need to call `$state`, `$derived` or `$effect` runes every time.
 *
 * If you also want to preprocess .svelte.js files, use `brefer` instead.
 *
 * @returns { import("svelte/compiler").PreprocessorGroup }
 */
export function breferPreprocess() {
	return {
		name: "brefer-preprocessor",
		async script({ content, filename }) {
			if (filename?.includes("/.svelte-kit/generated")) {
				return; // Ignored code generated by SvelteKit
			}

			return preprocessScript(content, filename);
		}
	};
}

/**
 * Brefer vite plugin for svelte. It allows to preprocess .svelte.js files as well as .svelte files.
 *
 * Prefer the use of `breferPreprocess` if you want to preprocess .svelte files only.
 *
 * @export
 * @param {import("./public.js").BreferConfig} config
 * @returns {import("vite").Plugin}
 */
export function brefer(config = {}) {
	const shouldProcess = createFilter(config.include, config.exclude);

	return {
		name: "vite-plugin-svelte-brefer",
		enforce: "pre",
		async transform(code, id) {
			if (!shouldProcess(id) || id.endsWith(".svelte")) {
				return;
			}

			if (id.endsWith(".svelte.js") || id.endsWith(".svelte.ts")) {
				const preprocessed = preprocessScript(code, id);

				return {
					code: preprocessed.code,
					map: preprocessed.map,
					id
				};
			}
		}
	};
}
